# Grid and time resolutions for building GridInputs, GridSets, and GridValues.
#
# Structure:
#   SystemName:
#     InputName:              # or 'default'
#       state_resolution: [nx, ny, nz, ...]
#       time_resolution: nt

RoverDark:
  RoverDark_MPC:
    state_resolution: [100, 100, 100]
    time_resolution: 100

  default:
    state_resolution: [100, 100, 100]
    time_resolution: 100

RoverBaseline:
  RoverBaseline_MPC:
    state_resolution: [100, 100, 100]
    time_resolution: 100

  default:
    state_resolution: [100, 100, 100]
    time_resolution: 100

RoverParam:
  RoverParam_MPC:
    # [px, py, theta, lambda] 
    # state_resolution: [100, 100, 100, 20]
    state_resolution: [51, 51, 51, 21]
    time_resolution: 101

  default:
    # state_resolution: [100, 100, 100, 20]
    state_resolution: [50, 50, 50, 10]
    time_resolution: 100

